### ISSUE TITLE
JSON comparison does not work with JsonUnit 3.0.0 and higher

### ISSUE THREAD

**Issue by azotcsit** [mock-server/mockserver-monorepo#1813]
**Describe the issue**
MockServer JSON body matching does not work when JsonUnit 3.0.0 and higher is in use. Basically, request matching fails with the following error:
```
java.lang.NoClassDefFoundError: net/javacrumbs/jsonunit/core/internal/Options
```
After a small digging, I found out that there was a refactoring made in JsonUnit (https://github.com/lukas-krecan/JsonUnit/pull/634) as a part of which `Options` class had been moved to another package (which is mentioned on their release notes: https://github.com/lukas-krecan/JsonUnit#300-2023-07-05). Therefore, MockServer is not anymore compatible with JsonUnit 3.0.0+.

Unfortunately, https://mvnrepository.com/artifact/org.mock-server/mockserver-core/5.15.0 suggests that MockServer is compatible with JsonUnit 3.2.2 which is not true.

**What you are trying to do**
I'm just trying to check/match JSON requests sent from a Spring application.

**MockServer version**
5.15.0

**To Reproduce**
Steps to reproduce the issue:

1. Use JsonUnit 3.0.0 and higher (I use 3.2.2 version)
2. Run MockServer from a JUnit test
3. Create an expectation with a JSON body
4. Send a request with the same JSON body (it will not match)

**Expected behaviour**
Request with the same JSON body matches

**Comment by jamesdbloom** [comment]
Closing — MockServer depends on json-unit-core 2.x which is incompatible with JsonUnit 3.0.0+ (the `Options` class was moved to a different package). MockServer targets Java 11 as minimum, and json-unit-core 3.x requires Java 17+, so we cannot upgrade.

**Workarounds:**
1. Use the `mockserver-netty-no-dependencies` (shaded) artifact instead of `mockserver-netty`. The shaded jar relocates all dependencies (including JsonUnit) to avoid classpath conflicts.
2. If you must use the non-shaded artifact, exclude `json-unit-core` from MockServer's transitive dependencies and keep your 3.x version — but be aware this may cause `NoClassDefFoundError` in MockServer's JSON matching.
